services:
  - type: web
    name: lab-arng
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: NOTION_TOKEN
        sync: false
      - key: DATABASE_ID
        sync: false
